'project_id': '507864'
'api_token': '9b1e8901250f148c9e919cd0d127897f62e3c260aba7ea65d776776a2255135efd219fd42b7d04d7'

'files': [{ 'source': '/i18n/**/*.json', 'translation': '/i18n/%two_letters_code%/%original_file_name%', 'update_option': 'update_as_unapproved' }]
