base_path: /i18n
files:
  - source: /en-US/*.json
    translation: /%locale%/%original_file_name%
  - source: /en-US/commands/**/*.json
    translation: /%locale%/%original_path%/%original_file_name%
  - source: /en-US/listeners/**/*.json
    translation: /%locale%/%original_path%/%original_file_name%
  - source: /en-US/preconditions/**/*.json
    translation: /%locale%/%original_path%/%original_file_name%
