base_path: /
files:
  - source: /i18n/en-US/*.json
    translation: /i18n/%locale%/%original_file_name%
  - source: /i18n/en-US/commands/**/*.json
    translation: /%locale%/%original_path%/%original_file_name%
  - source: /i18n/en-US/listeners/**/*.json
    translation: /%locale%/%original_path%/%original_file_name%
  - source: /i18n/en-US/preconditions/**/*.json
    translation: /%locale%/%original_path%/%original_file_name%
